# Generated by Django 2.1.5 on 2019-01-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0003_auto_20190129_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameuser',
            name='server_name',
            field=models.CharField(choices=[('A', 'A서버'), ('B', 'B서버'), ('C', 'C서버')], max_length=10),
        ),
    ]
